name: ci(cache)

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: v1-${{ runner.os }}-buildx-${{ env.HEAD_SHA }}
          restore-keys: |
            v1-${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          # https://github.com/docker/buildx/issues/206
          driver-opts: image=moby/buildkit:master
      
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          # https://github.com/docker/buildx/issues/73
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

